defmodule Mix.Tasks.Defdo.Repo.CompiledConfig do
  @shortdoc "Generates the defdo repo flavour config file"

  @moduledoc """
  Writes the compiled config file that gives a defdo app its repo flavour:
  schema-scoped `search_path`, per-schema `schema_migrations`, `binary_id` keys
  and `timestamptz` timestamps.

      mix defdo.repo.compiled_config
      mix defdo.repo.compiled_config --filename extra_config
      mix defdo.repo.compiled_config --check

  ## Why `--check` exists

  This file is generated once and then committed, so it drifts. Five variants of
  it exist across the estate and two of them return `[type: :timestamptz]` from
  `migration_primary_key/1` and `migration_foreign_key/1` where the generator
  emits `[type: :binary_id]` — every migration written against those two builds
  primary and foreign keys of the wrong type, silently.

  `--check` reports that drift without writing anything and exits 1 if it finds
  any, so it can be a CI step.

  ## Options

    * `--filename` — defaults to `defdo_compiled_config.exs`
    * `--check` — report drift, write nothing, exit 1 on findings
    * `--force` — overwrite an existing file (without it, an existing file is
      left alone and reported)
  """

  use Mix.Task

  alias Defdo.Tasks.Saas.Audit

  @default_filename "defdo_compiled_config.exs"

  @impl Mix.Task
  def run(args) do
    valid_options = [filename: :string, check: :boolean, force: :boolean]

    case OptionParser.parse_head!(args, switches: valid_options) do
      {opts, []} ->
        if opts[:check], do: check(), else: new(opts[:filename], opts)

      {_, _} ->
        error()
    end
  end

  defp check do
    case Audit.check_compiled_config(config_dir()) do
      [] ->
        Mix.shell().info("defdo.repo.compiled_config: no drift found in #{config_dir()}.")

      findings ->
        for finding <- findings, do: Mix.shell().error("DRIFT #{finding.message}")
        exit({:shutdown, 1})
    end
  end

  def new(filename, opts \\ [])
  def new(nil, opts), do: new(@default_filename, opts)

  def new(filename, opts) do
    config_dir = config_dir()
    filename = ensure_extension(filename)
    path = Path.join(config_dir, filename)

    cond do
      not File.exists?(path) ->
        File.write!(path, compiled_config())
        hint(filename)

      opts[:force] ->
        File.write!(path, compiled_config())
        Mix.shell().info("Overwrote #{path}.")
        hint(filename)

      true ->
        Mix.shell().info("""
        #{path} already exists and was left alone.

        Apps in this estate have deliberately extended this file -- with a
        `migration_default_prefix/0`, or a `Code.ensure_loaded?` guard -- and
        overwriting it would drop those. Run `--check` to see whether it has drifted in a
        way that matters, or `--force` to regenerate it anyway.
        """)
    end
  end

  defp ensure_extension(filename) do
    case Path.extname(filename) do
      "" ->
        "#{filename}.exs"

      ".exs" ->
        filename

      _ ->
        Mix.raise("""
        Only .exs extension is allowed for the filename.

        You provided the filename: `#{filename}` which is not a valid name.
        """)
    end
  end

  defp compiled_config do
    ~S'# Generated by `mix defdo.repo.compiled_config`.
#
# Guarded so a dependency that already defines this module wins instead of
# colliding -- several apps in the estate added this guard by hand.
unless Code.ensure_loaded?(Defdo.Repo.CompileConfig) do
  defmodule Defdo.Repo.CompileConfig do
    @moduledoc """
    Provide a flavour to configure repo options for defdo apps.
    """
    def schema(name \\ otp_app()),
      # If you wish to use another schema for your deployment
      # just give the schema to use through an environment variable.
      do: System.get_env("TENANT_APP_SCHEMA", "#{name}")

    # The schema defdo package migrators run their wrappers against. Kept as its
    # own function because migrations read it by name.
    def migration_default_prefix(name \\ otp_app()), do: schema(name)

    def after_connect(extra_schemas \\ [])

    def after_connect(extra_schemas) when is_bitstring(extra_schemas),
      do: extra_schemas |> String.split(",", trim: true) |> after_connect()

    def after_connect(extra_schemas) when is_list(extra_schemas) do
      search_path = Enum.join([schema() | extra_schemas] ++ ~w(public), ",")

      {Postgrex, :query!, ["SET search_path TO #{search_path}", []]}
    end

    def migration_source(schema \\ "") when is_bitstring(schema) do
      ["schema_migrations", schema]
      |> Enum.reject(&(&1 == ""))
      |> Enum.join("_")
    end

    def migration_timestamps(extras \\ []) when is_list(extras),
      do: [type: :timestamptz] ++ extras

    def migration_primary_key(extras \\ []) when is_list(extras),
      do: [type: :binary_id] ++ extras

    def migration_foreign_key(extras \\ []) when is_list(extras),
      do: [type: :binary_id] ++ extras

    def otp_app do
      module = Mix.Project.get()
      apply(module, :project, [])[:app]
    end
  end
end'
  end

  def config_dir do
    {:ok, filename} = Mix.Project.config()[:config_path] |> Path.safe_relative_to(".")
    config_dir = Path.dirname(filename)

    if File.dir?(config_dir) do
      config_dir
    else
      File.mkdir_p(config_dir)
      config_dir
    end
  end

  def hint(filename) do
    Mix.shell().info("""
    Update your config/config.exs with the following information

    import_config "#{filename}"
    alias Defdo.Repo.CompileConfig, as: RepoCompileConfig

      # Use a flavored flow within schema
      config :#{otp_app()}, MyApp.Repo,
        migration_source: RepoCompileConfig.migration_source(),
        migration_timestamps: RepoCompileConfig.migration_timestamps(),
        migration_primary_key: RepoCompileConfig.migration_primary_key(),
        migration_foreign_key: RepoCompileConfig.migration_foreign_key(),
        migration_default_prefix: RepoCompileConfig.migration_default_prefix(),
        after_connect: RepoCompileConfig.after_connect()
    """)
  end

  defp error do
    Mix.raise("""
    Invalid arguments to defdo.repo.compiled_config, expects one of:

        mix defdo.repo.compiled_config
        mix defdo.repo.compiled_config --filename extra_config
        mix defdo.repo.compiled_config --filename extra_config.exs
        mix defdo.repo.compiled_config --check
        mix defdo.repo.compiled_config --force
    """)
  end

  defp otp_app do
    module = Mix.Project.get()
    apply(module, :project, [])[:app]
  end
end
